### ISSUE TITLE
Duplication of an item

### ISSUE THREAD

**Issue by Brand3000** [outl1ne/nova-sortable#161]
Hase somebody come across a situation when moving a penultimate item to the last position causes a duplicate of the moved item?

**Comment by xuchunyang** [comment]
I just encountered the issue, the duplication only shows in the web, after refresh it disappears

**Comment by Navi2016** [comment]
Had same issue! Fresh install of latest version of ext on latest Nova.

**Comment by scouser03** [comment]
I have same problem.  anyone solved it ?

**Comment by kiritokatklian** [comment]
Same here. It happens when moving any item to any position.
The only exception is when you move the one at the bottom of the list one position up.

@KasparRosin any ideas as to what might cause this issue? It's not actually creating a duplicate as much as it's retaining the old position (ghost item) + the new position (actual item)

**Comment by Tarpsvo** [comment]
I think I found a weird Vue3 bug with keys that caused this. Should be fixed in version 3.4.3. Please test it. Thanks!
